from django.core.management.base import BaseCommand
from admission.models import Course


class Command(BaseCommand):
    help = 'Populate course database with sample courses for recommendation system'

    def handle(self, *args, **options):
        # Clear existing courses if any
        Course.objects.all().delete()

        # Course data based on website
        courses_data = [
            {
                'code': 'BTECH',
                'name': 'B.Tech',
                'full_name': 'Bachelor of Technology',
                'duration': '4 Years',
                'seats': 120,
                'education_level': '10+2',
                'required_stream': 'PCM',
                'min_percentage': 50.00,
                'annual_fee': 100000,
                'total_fee': 400000,
                'description': 'Engineering programs in CSE, ECE, ME, CE branches with industry-ready curriculum.',
                'career_opportunities': 'Software Engineer, Hardware Engineer, Systems Engineer, Project Manager, Tech Lead, Engineering Manager',
                'average_salary': '6-12 LPA',
                'icon': '🔧',
            },
            {
                'code': 'BCA',
                'name': 'BCA',
                'full_name': 'Bachelor of Computer Applications',
                'duration': '3 Years',
                'seats': 60,
                'education_level': '10+2',
                'required_stream': 'ANY',
                'min_percentage': 45.00,
                'annual_fee': 70000,
                'total_fee': 210000,
                'description': 'Comprehensive computer science program covering programming, databases and web development.',
                'career_opportunities': 'Web Developer, Mobile App Developer, Database Administrator, System Analyst, IT Support Specialist',
                'average_salary': '4-8 LPA',
                'icon': '💻',
            },
            {
                'code': 'BBA',
                'name': 'BBA',
                'full_name': 'Bachelor of Business Administration',
                'duration': '3 Years',
                'seats': 60,
                'education_level': '10+2',
                'required_stream': 'ANY',
                'min_percentage': 45.00,
                'annual_fee': 60000,
                'total_fee': 180000,
                'description': 'Management fundamentals, marketing, finance and entrepreneurship skills.',
                'career_opportunities': 'Business Analyst, Marketing Manager, HR Manager, Finance Manager, Entrepreneur, Management Consultant',
                'average_salary': '4-7 LPA',
                'icon': '📊',
            },
            {
                'code': 'MBA',
                'name': 'MBA',
                'full_name': 'Master of Business Administration',
                'duration': '2 Years',
                'seats': 60,
                'education_level': 'GRADUATION',
                'required_stream': 'ANY',
                'min_percentage': 50.00,
                'annual_fee': 150000,
                'total_fee': 300000,
                'description': 'Advanced management education with specializations in Finance, HR, Marketing.',
                'career_opportunities': 'Senior Manager, Strategy Consultant, Investment Banker, Management Executive, Business Leader',
                'average_salary': '8-15 LPA',
                'icon': '🏢',
            },
            {
                'code': 'MTECH',
                'name': 'M.Tech',
                'full_name': 'Master of Technology',
                'duration': '2 Years',
                'seats': 30,
                'education_level': 'GRADUATION',
                'required_stream': 'PCM',
                'min_percentage': 55.00,
                'annual_fee': 120000,
                'total_fee': 240000,
                'description': 'Advanced technical specialization with research opportunities.',
                'career_opportunities': 'Research Engineer, Technology Specialist, Senior Software Engineer, Technical Lead, Innovation Manager',
                'average_salary': '7-12 LPA',
                'icon': '⚙️',
            },
            {
                'code': 'BCOM',
                'name': 'B.Com',
                'full_name': 'Bachelor of Commerce',
                'duration': '3 Years',
                'seats': 60,
                'education_level': '10+2',
                'required_stream': 'COMMERCE',
                'min_percentage': 45.00,
                'annual_fee': 50000,
                'total_fee': 150000,
                'description': 'Accounting, taxation, business law and financial management.',
                'career_opportunities': 'Chartered Accountant, Tax Consultant, Auditor, Financial Analyst, Company Secretary',
                'average_salary': '4-9 LPA',
                'icon': '💰',
            },
            {
                'code': 'BSC',
                'name': 'B.Sc',
                'full_name': 'Bachelor of Science',
                'duration': '3 Years',
                'seats': 60,
                'education_level': '10+2',
                'required_stream': 'PCM',
                'min_percentage': 45.00,
                'annual_fee': 40000,
                'total_fee': 120000,
                'description': 'Physics, Chemistry, Mathematics, Biology specializations available.',
                'career_opportunities': 'Research Scientist, Laboratory Technician, Science Teacher, Data Analyst, Quality Analyst',
                'average_salary': '3-6 LPA',
                'icon': '🔬',
            },
            {
                'code': 'BPHARM',
                'name': 'B.Pharm',
                'full_name': 'Bachelor of Pharmacy',
                'duration': '4 Years',
                'seats': 60,
                'education_level': '10+2',
                'required_stream': 'PCB',
                'min_percentage': 50.00,
                'annual_fee': 80000,
                'total_fee': 320000,
                'description': 'Pharmaceutical sciences with hands-on lab training and clinical exposure.',
                'career_opportunities': 'Pharmacist, Pharmaceutical Researcher, Medical Representative, Quality Assurance Officer, Hospital Pharmacist',
                'average_salary': '4-9 LPA',
                'icon': '💊',
            },
            {
                'code': 'BSC_MSC',
                'name': 'B.Sc + M.Sc',
                'full_name': 'Bachelor + Master of Science (Integrated)',
                'duration': '5 Years',
                'seats': 30,
                'education_level': '10+2',
                'required_stream': 'PCM',
                'min_percentage': 60.00,
                'annual_fee': 45000,
                'total_fee': 225000,
                'description': 'Integrated program combining bachelor and master degrees in science with research focus.',
                'career_opportunities': 'Research Scientist, University Professor, Research Fellow, Innovation Specialist, Government Scientist',
                'average_salary': '5-10 LPA',
                'icon': '🔭',
            },
        ]

        # Create courses
        for course_info in courses_data:
            course = Course.objects.create(**course_info)
            self.stdout.write(self.style.SUCCESS(f"✓ Created: {course.name} ({course.code})"))

        self.stdout.write(self.style.SUCCESS(f"\n✅ Successfully added {len(courses_data)} courses to the database!"))
