# Generated by Django 4.2.29 on 2026-03-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('course', models.CharField(choices=[('BCA', 'BCA - Bachelor of Computer Applications'), ('BBA', 'BBA - Bachelor of Business Administration'), ('MBA', 'MBA - Master of Business Administration'), ('BTECH', 'B.Tech - Bachelor of Technology'), ('MTECH', 'M.Tech - Master of Technology'), ('BCOM', 'B.Com - Bachelor of Commerce'), ('MCOM', 'M.Com - Master of Commerce'), ('BSC', 'B.Sc - Bachelor of Science'), ('MSC', 'M.Sc - Master of Science'), ('BA', 'BA - Bachelor of Arts'), ('MA', 'MA - Master of Arts'), ('LLB', 'LLB - Bachelor of Laws'), ('BPHARM', 'B.Pharm - Bachelor of Pharmacy')], max_length=10, verbose_name='Applied Course')),
                ('address', models.TextField(verbose_name='Residential Address')),
                ('father_name', models.CharField(default='', max_length=200, verbose_name="Father's Name")),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('tenth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='10th Percentage')),
                ('twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='12th Percentage')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Application Status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of Submission')),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
