# Generated by Django 4.2.29 on 2026-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Course Code')),
                ('name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Course Name')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration (Years)')),
                ('seats', models.IntegerField(verbose_name='Available Seats')),
                ('education_level', models.CharField(choices=[('10+2', '10+2 (12th Pass)'), ('GRADUATION', 'Graduation'), ('POST_GRADUATION', 'Post Graduation')], max_length=20, verbose_name='Required Education Level')),
                ('required_stream', models.CharField(choices=[('PCM', 'Science (PCM)'), ('PCB', 'Science (PCB)'), ('COMMERCE', 'Commerce'), ('ARTS', 'Arts'), ('ANY', 'Any Stream')], max_length=20, verbose_name='Required Stream')),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minimum Percentage')),
                ('annual_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Annual Fee (INR)')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Course Fee (INR)')),
                ('description', models.TextField(verbose_name='Course Description')),
                ('career_opportunities', models.TextField(help_text='List of job roles and industries', verbose_name='Career Opportunities')),
                ('average_salary', models.CharField(help_text='e.g., 4-8 LPA', max_length=100, verbose_name='Average Salary Range')),
                ('icon', models.CharField(default='📚', max_length=10, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
            },
        ),
    ]
